<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RoseMcp.Contracts\RoseMcp.Contracts.csproj" />
    <ProjectReference Include="..\RoseMcp.Solutions\RoseMcp.Solutions.csproj" />
  </ItemGroup>

</Project>
