using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace RoseMcp.Worker.Xaml;

/// <summary>
/// Writes the partial class a XAML file would have generated, with no runnable code in it.
/// <para>
/// The aim is only that the code-behind binds: its base type, its named fields, and the members the
/// real generator declares that hand-written code refers to. Nothing here loads markup or builds a
/// visual tree, and it never reaches disk.
/// </para>
/// </summary>
public static class XamlStubEmitter
{
	/// <summary>
	/// Broad by intention. These stubs go into other people's projects, where nullable warnings,
	/// missing documentation and hiding an inherited member are frequently errors -- and a stub that
	/// trades 2000 errors for 200 different ones has not helped anybody.
	/// </summary>
	private const string Pragmas = "#pragma warning disable 0108, 0109, 0114, 0169, 0649, 1591";

	/// <summary>
	/// The nullable half, separate because it cannot go into a project older than C# 8. An SDK-style
	/// .NET Framework project defaults to C# 7.3, where <c>#nullable disable</c> is CS8370 -- three
	/// errors of our own making in a file that was meant to remove them. Found by loading a net48 WPF
	/// project, which is why the language version is asked rather than assumed from the framework.
	/// </summary>
	private const string NullablePragmas = "#pragma warning disable 8618, 8625";

	public static XamlStubEmission Emit(Compilation compilation, IXamlDialect dialect, XamlDocument document)
	{
		if (document.ClassName is not { Length: > 0 }) return XamlStubEmission.Skipped("no x:Class");

		if (Lookup(compilation, document.ClassName) is not { } symbol)
		{
			return XamlStubEmission.Skipped($"no class {document.ClassName} in this project");
		}

		// The real partial is present -- some project shapes do put it in the compilation -- so
		// generating a second one would be a pile of duplicate members.
		if (symbol.GetMembers("InitializeComponent").Length > 0)
		{
			return XamlStubEmission.Skipped("the generated partial is already in the compilation");
		}

		var unresolved = new List<string>();
		var fields = new List<string>();

		foreach (var element in document.NamedElements)
		{
			// Never redeclare what the hand-written half already has; that is a duplicate member
			// rather than a fix.
			if (symbol.GetMembers(element.Name).Length > 0) continue;

			// A named root can be typed as the class itself, which needs no resolution: the class was
			// found above, and it is by construction a subtype of whatever the markup names.
			var declared = element.IsRoot && dialect.RootFieldIsTheClass
				? symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
				: Resolve(compilation, dialect, element.Type);

			if (declared is not { } type)
			{
				unresolved.Add($"{element.Name}: {Describe(element.Type)}");
				continue;
			}

			fields.Add($"{element.Modifier ?? dialect.DefaultFieldModifier} {type} {element.Name};");
		}

		// Only when no other part declares one: two partials naming different base classes is
		// CS0263, which is worse than the missing base we started with.
		var baseType = symbol.BaseType is null || symbol.BaseType.SpecialType == SpecialType.System_Object
			? Resolve(compilation, dialect, document.RootType)
			: null;

		return new XamlStubEmission
		{
			HintName = $"{document.ClassName}.xamlstub.g.cs",
			Source = Compose(compilation, document, dialect, baseType, fields),
			SkipReason = null,
			UnresolvedTypes = unresolved,
		};
	}

	private static string Compose(
		Compilation compilation,
		XamlDocument document,
		IXamlDialect dialect,
		string? baseType,
		IReadOnlyList<string> fields)
	{
		var body = new StringBuilder();

		foreach (var field in fields)
		{
			body.Append('\t').Append(field).Append('\n');
		}

		if (fields.Count > 0) body.Append('\n');

		// Public because the frameworks generate it public, and code outside the class calls it.
		body.Append("\tpublic void InitializeComponent()\n\t{\n\t}\n");

		// An exe whose entry point the markup compiler would have generated is CS5001 without it.
		// Guarded on there being none already, so a hand-written Main always wins.
		if (document.IsApplicationDefinition && NeedsEntryPoint(compilation))
		{
			body.Append("\n\tpublic static void Main(string[] args)\n\t{\n\t}\n");
		}

		foreach (var member in dialect.ExtraMembers(document))
		{
			body.Append('\t').Append(member).Append('\n');
		}

		var declaration = baseType is null
			? $"partial class {document.TypeName}"
			: $"partial class {document.TypeName} : {baseType}";

		var source = new StringBuilder();
		source.Append("// <auto-generated/>\n");
		source.Append("// Synthesised by RoseMCP from ").Append(document.Path).Append('\n');
		source.Append("// The markup compiler runs only in a real build, so this stands in for what it\n");
		source.Append("// would have generated. It declares; it does not do anything.\n");
		source.Append(Pragmas).Append('\n');

		if (SupportsNullable(compilation))
		{
			source.Append("#nullable disable\n");
			source.Append(NullablePragmas).Append('\n');
		}

		source.Append('\n');

		if (document.Namespace.Length == 0)
		{
			source.Append(declaration).Append('\n').Append("{\n").Append(body).Append("}\n");

			return source.ToString();
		}

		source.Append("namespace ").Append(document.Namespace).Append('\n').Append("{\n");
		source.Append('\t').Append(declaration).Append('\n').Append("\t{\n");

		foreach (var line in body.ToString().Split('\n'))
		{
			source.Append(line.Length == 0 ? string.Empty : "\t").Append(line).Append('\n');
		}

		source.Append("\t}\n").Append("}\n");

		return source.ToString();
	}

	/// <summary>
	/// The CLR type an element names, fully qualified, or null when this project cannot see it.
	/// <para>
	/// Everything comes out of the project's own reference set, so a third-party control resolves
	/// because its assembly is referenced and an in-house control resolves through the project that
	/// declares it. No table of framework types is hardcoded anywhere.
	/// </para>
	/// </summary>
	private static string? Resolve(Compilation compilation, IXamlDialect dialect, XamlTypeName name)
	{
		if (name.ClrNamespace is { Length: > 0 } declared)
		{
			return Lookup(compilation, $"{declared}.{name.LocalName}")?.ToDisplayString(
				SymbolDisplayFormat.FullyQualifiedFormat);
		}

		if (!name.IsFrameworkType) return null;

		foreach (var candidate in dialect.FrameworkNamespaces)
		{
			if (Lookup(compilation, $"{candidate}.{name.LocalName}") is { } found)
			{
				return found.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			}
		}

		return null;
	}

	/// <summary>
	/// The singular lookup returns nothing when two assemblies define the same name, which is
	/// ordinary in a migration where a projection and a shim overlap. Taking the first of the
	/// several is better than reporting the type as missing.
	/// </summary>
	private static INamedTypeSymbol? Lookup(Compilation compilation, string metadataName) =>
		compilation.GetTypeByMetadataName(metadataName)
			?? compilation.GetTypesByMetadataName(metadataName).FirstOrDefault();

	/// <summary>
	/// Whether this project is an executable with no Main of its own. Asked by declaration lookup
	/// rather than through GetEntryPoint, which would bind the entry point from inside the generator
	/// that is still producing source for it.
	/// </summary>
	private static bool NeedsEntryPoint(Compilation compilation)
	{
		if (compilation.Options.OutputKind is not (OutputKind.ConsoleApplication or OutputKind.WindowsApplication))
		{
			return false;
		}

		return !compilation.GetSymbolsWithName("Main", SymbolFilter.Member)
			.OfType<IMethodSymbol>()
			.Any(method => method.IsStatic);
	}

	/// <summary>
	/// Whether this project's language version understands the nullable directives. Taken from the
	/// compilation rather than from the target framework, because the two are independent: a net48
	/// project that sets LangVersion is as common as one that leaves it at the default.
	/// </summary>
	private static bool SupportsNullable(Compilation compilation) =>
		compilation is not CSharpCompilation csharp || csharp.LanguageVersion >= LanguageVersion.CSharp8;

	private static string Describe(XamlTypeName type) =>
		type.IsFrameworkType ? type.LocalName : $"{type.NamespaceUri}:{type.LocalName}";
}
