// RoseMcp.Xaml.WinUi.Tap: a XAML Diagnostics provider (TAP) injected into a running WinUI 3 app.
//
// The sibling of RoseMcp.Xaml.Uwp.Tap, named for the XAML framework it binds to rather than the app
// model: everything here is Microsoft.UI.Xaml, which packaged and unpackaged WinUI 3 both use.
//
// Almost none of this file is code. The implementation lives in ../RoseMcp.Xaml.Tap, shared verbatim
// with the UWP provider (#73), and what a provider supplies is its identity, its projections, the six
// aliases those are bound to, its class id, and one pointer hook (#75). That the shared half needed
// no edits at all to serve a second framework is the whole claim of the split, and this file is the
// test of it.
//
// Three things differ from UWP in ways that are not naming, and all three were measured rather
// than assumed:
//
//   * InitializeXamlDiagnosticsEx is NOT exported from Microsoft.UI.Xaml.dll. WinUI 3 exports eight
//     functions from it and that is not among them. It lives in Microsoft.Internal.FrameworkUdk.dll,
//     in the WindowsAppRuntime framework package. The host resolves it from the target's own loaded
//     modules, which is the only way to get the right version and architecture.
//
//   * There is no CoreWindow, and no ambient Window.Current. See RoseTapWatchPointer below.
//
//   * The tree walk may not be advised from the UI thread, which is the thread WinUI 3 sites the
//     tap on. See RoseTapRunTapBody below; it is the only reason this provider needs a thread.

#include <windows.h>
#include <unknwn.h>
#include <ocidl.h>

#undef GetCurrentTime

#include <xamlOM.h>

// Identity, before the channel that logs through it. Two providers may serve one machine and write
// adjacent work folders, so the log has to name which of them wrote it.
static const wchar_t* const RoseTapName = L"RoseMcp.Xaml.WinUi.Tap";
static const wchar_t* const RoseTapLogFile = L"\\rosemcp.xaml.winui.tap.log";

// The framework-free channel, then the xamlOM ABI layer. xamlOM.h is shared by both frameworks
// verbatim -- the interfaces, the handles and the enums are the same declarations -- which is why
// tap_diagnostics.h needs no WinUI variant. Both before the projections, as the original required.
#include "../RoseMcp.Xaml.Tap/tap_channel.h"
#include "../RoseMcp.Xaml.Tap/tap_diagnostics.h"

// C++/WinRT projections. Generated by build.ps1 with cppwinrt.exe from the WindowsAppSDK's winmds,
// because unlike Windows.UI.Xaml these are not in the Windows SDK (#76). The generated set includes
// the Windows.* projections too, so everything below comes from one consistent generation.
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.UI.h> // Color
#include <winrt/Microsoft.UI.Xaml.h>
#include <winrt/Microsoft.UI.Xaml.Controls.h>
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h> // ButtonBase::Click, or it is "auto before defined"
#include <winrt/Microsoft.UI.Xaml.Media.h>
#include <winrt/Microsoft.UI.Xaml.Media.Animation.h> // Storyboard and DoubleAnimation, for the proximity fades
#include <winrt/Microsoft.UI.Xaml.Shapes.h> // Rectangle and Path, for the outlines and the mark
#include <winrt/Microsoft.UI.Xaml.Input.h>
#include <winrt/Microsoft.UI.Input.h>   // InputPointerSource, which is what replaces CoreWindow
#include <winrt/Microsoft.UI.Content.h> // ContentIsland, which is what it is asked of
#include <winrt/Microsoft.UI.Dispatching.h> // DispatcherQueue, for getting back onto the UI thread

namespace xaml = winrt::Microsoft::UI::Xaml;
namespace xcontrols = winrt::Microsoft::UI::Xaml::Controls;
namespace xmedia = winrt::Microsoft::UI::Xaml::Media;
namespace xanim = winrt::Microsoft::UI::Xaml::Media::Animation;
namespace xinput = winrt::Microsoft::UI::Xaml::Input;
namespace xshapes = winrt::Microsoft::UI::Xaml::Shapes;

// {2af9a655-49a7-43ee-b6fc-ff579688d311}
//
// Its own, and it has to be: both providers may be staged on one machine, and the host names the
// class it wants when it injects.
static const CLSID CLSID_RoseTap =
{ 0x2af9a655, 0x49a7, 0x43ee, { 0xb6, 0xfc, 0xff, 0x57, 0x96, 0x88, 0xd3, 0x11 } };

// The overlay's one genuine seam (#75): a passive observer of pointer movement, used for the
// proximity fade that gets the marks out of the way. Two properties are required, and neither is
// negotiable -- it must consume nothing, and it must see moves the app has already marked handled.
//
// WinUI 3 has no CoreWindow, so this is InputPointerSource on the window's content island. That it
// preserves both properties was measured rather than assumed, because #75 doubted it: on a real
// WinUI 3 app, 41 pointer moves over plain content and then 33 over an element whose handler sets
// Handled, the island's source counted all 74 while the app's own root handler counted the 41 and
// none of the 33. So it sees what the app has handled, and takes nothing away from the app.
//
// Unlike UWP there is no ambient window to ask, which is why the anchor is in the signature at all:
// the island is reached through the element's XamlRoot.
//
// Positions arrive in the island's coordinate space. The diagnostics UI layer is sized to that same
// content area, so no transform is applied here -- if a WinUI target ever shows the marks offset by
// a constant, this is the line to doubt first.
static bool RoseTapWatchPointer(
	xaml::UIElement const& anchor,
	std::function<void(winrt::Windows::Foundation::Point const&)> onMove,
	std::function<void()> onExit)
{
	// Each step says so on its own. The caller only reports that the fade is off, and four ways to
	// arrive at that answer are not the same finding -- which is the lesson the rest of this
	// provider was taught the hard way.
	if (!anchor)
	{
		Log(L"pointer: no anchor element");
		return false;
	}

	const auto root = anchor.XamlRoot();
	if (!root)
	{
		Log(L"pointer: the anchor has no XamlRoot");
		return false;
	}

	auto island = root.ContentIsland();
	if (!island)
	{
		// XamlRoot.ContentIsland answers only for a XamlIsland-based content root -- XamlRoot_Partial.cpp
		// asks GetContentRootNoRef()->GetXamlIslandRootNoRef() and returns null otherwise -- and the
		// diagnostics UI layer this anchors on does not report one. The islands the thread owns are the
		// same content reached another way, and this always runs on the UI thread, so asking is valid.
		// Measured rather than assumed, twice over: the thread owns exactly one island, so taking the
		// first is not a guess, and a sweep of 40 synthetic moves across the window was observed as 40
		// through the source acquired from it. Before this fallback the seam went quiet on every WinUI
		// target and cost only the fade, which is the kind of silence that survives for months.
		const auto owned = winrt::Microsoft::UI::Content::ContentIsland::FindAllForCurrentThread();
		Log(L"pointer: the XamlRoot has no ContentIsland; the thread owns " + std::to_wstring(owned.size()));
		if (owned.size() > 0) island = owned[0];
	}

	if (!island)
	{
		Log(L"pointer: no ContentIsland to observe");
		return false;
	}

	const auto source = winrt::Microsoft::UI::Input::InputPointerSource::GetForIsland(island);
	if (!source)
	{
		Log(L"pointer: the ContentIsland has no InputPointerSource");
		return false;
	}

	source.PointerMoved(
		[onMove](winrt::Microsoft::UI::Input::InputPointerSource const&,
			winrt::Microsoft::UI::Input::PointerEventArgs const& e)
		{
			onMove(e.CurrentPoint().Position());
		});

	source.PointerExited(
		[onExit](winrt::Microsoft::UI::Input::InputPointerSource const&,
			winrt::Microsoft::UI::Input::PointerEventArgs const&)
		{
			onExit();
		});

	return true;
}

// Where the tap body runs, and the second thing about WinUI 3 that is a difference in kind rather
// than in naming (#76).
//
// WinUI 3 dispatches tap creation onto the UI thread (DebugTool::Create posts SetSite through the
// XAML dispatcher), and its AdviseVisualTreeChange enqueues the tree walk back onto that same
// thread and then blocks the caller until it finishes -- Advising::RunOnUIThread, with no check for
// already being on it. Advising from SetSite therefore blocks the only thread that can serve the
// walk, forever. Nothing is logged, nothing returns, and no callback arrives, so it presents as the
// framework having ignored the tap entirely; it cost days on exactly that reading. UWP has no such
// constraint because it enumerates inline.
//
// So the body runs on a thread of its own, and the part that touches XAML is sent back. The same
// seam carries the pipe reader (#50), which needs the UI thread for the same reason from a different
// direction.
//
// The queue comes from IXamlDiagnostics::GetDispatcher rather than from GetForCurrentThread. That is
// a xamlOM method, so the shared half asks for it and only the cast is here -- and unlike asking the
// current thread it answers from anywhere, which the reader thread needs and the worker thread this
// provider creates needs too.
static winrt::Microsoft::UI::Dispatching::DispatcherQueue g_uiQueue{ nullptr };
static DWORD g_uiThreadId = 0;

static void RoseTapCaptureDispatcher(::IInspectable* raw)
{
	g_uiThreadId = ::GetCurrentThreadId();
	if (!raw) return;

	winrt::Windows::Foundation::IInspectable dispatcher{ nullptr };
	winrt::attach_abi(dispatcher, raw); // adopt the ref
	if (!g_uiQueue) g_uiQueue = dispatcher.try_as<winrt::Microsoft::UI::Dispatching::DispatcherQueue>();

	Log(g_uiQueue ? L"SetSite: holding the UI dispatcher" : L"SetSite: no DispatcherQueue available");
}

static void RoseTapRunTapBody(std::function<void()> body)
{
	std::thread([body = std::move(body)]()
	{
		// Multi-threaded, because nothing here is apartment-bound: the diagnostics pointers are used
		// in-process and the DispatcherQueue is agile. What must not happen is running this on the UI
		// thread's apartment, which is the whole point of the thread.
		const HRESULT hr = CoInitializeEx(nullptr, COINIT_MULTITHREADED);
		body();
		if (SUCCEEDED(hr)) CoUninitialize();
	}).detach();
}

// Blocking is deliberate and safe here in a way it is not the other way round: this is a worker
// waiting on the UI thread, never the UI thread waiting on itself. The thread-id check is what makes
// that true rather than hoped for.
static bool RoseTapRunOnUiThread(const std::function<void()>& work)
{
	if (::GetCurrentThreadId() == g_uiThreadId)
	{
		work();
		return true;
	}

	if (!g_uiQueue) return false;

	const HANDLE done = CreateEventW(nullptr, TRUE, FALSE, nullptr);
	if (!done) return false;

	const bool enqueued = g_uiQueue.TryEnqueue([&work, done]()
	{
		work();
		SetEvent(done);
	});

	if (enqueued) WaitForSingleObject(done, INFINITE);
	else Log(L"the UI thread's DispatcherQueue refused the work");

	CloseHandle(done);
	return enqueued;
}

// The two layers that need the aliases and the class id above: the overlay is written against the
// six aliases, and the COM object needs CLSID_RoseTap to answer DllGetClassObject.
#include "../RoseMcp.Xaml.Tap/tap_overlay.h"
#include "../RoseMcp.Xaml.Tap/tap_object.h"
