using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace RoseMcp.Worker;

/// <summary>
/// Whether code was written by a tool rather than a person, which decides whether a write may go
/// there at all.
/// <para>
/// Two kinds, and only one of them is missing from disk. A source generator's output is a
/// <see cref="SourceGeneratedDocument"/>, and the solution hands it back for its syntax tree with a
/// path of its own, so asking whether there is a document, or whether it has a path, says nothing. A
/// XAML compiler's <c>.g.i.cs</c> and a designer's <c>.designer.cs</c> are ordinary documents in the
/// project, on disk under <c>obj</c> or beside the file they were made from. Both are rewritten on the
/// next build, so an edit to either is lost, and a partial type with one hand-written half and seven
/// generated ones has one place a member can go.
/// </para>
/// </summary>
public static class GeneratedCode
{
	/// <summary>Whether a document is generated: by a source generator, by the build, or by a designer.</summary>
	public static bool Is(Document document) =>
		document is SourceGeneratedDocument
			|| document.FilePath is not { Length: > 0 } path
			|| IsGeneratedFile(path);

	/// <summary>
	/// Whether a declaration is generated: its document is, its file opens with the
	/// <c>&lt;auto-generated&gt;</c> comment generated code is marked with, or it carries
	/// <c>[GeneratedCode]</c>.
	/// <para>
	/// The two markers are the ones a generator writes for every other tool to read, and each catches
	/// what the other misses. The comment is about the whole file, so it covers a generator's half of a
	/// partial type, which is never itself attributed. The attribute is about one member, and covers the
	/// generated members of a file a person also writes in, such as a designer's.
	/// </para>
	/// </summary>
	public static bool Is(Document document, SyntaxNode declaration) =>
		Is(document) || OpensAsGenerated(declaration.SyntaxTree) || Attributed(declaration);

	/// <summary>
	/// Whether the comments a file opens with say it is generated, the way the compiler's own analyzers
	/// decide it: <c>&lt;auto-generated&gt;</c> or <c>&lt;autogenerated&gt;</c> before the first token.
	/// </summary>
	private static bool OpensAsGenerated(SyntaxTree tree) =>
		tree.GetRoot().GetLeadingTrivia()
			.Where(trivia => trivia.IsKind(SyntaxKind.SingleLineCommentTrivia) || trivia.IsKind(SyntaxKind.MultiLineCommentTrivia))
			.Any(trivia => trivia.ToString().Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)
				|| trivia.ToString().Contains("<autogenerated", StringComparison.OrdinalIgnoreCase));

	/// <summary>Whether the declaration carries <c>[GeneratedCode]</c>, by any spelling of its name.</summary>
	private static bool Attributed(SyntaxNode declaration) =>
		declaration is MemberDeclarationSyntax member
		&& member.AttributeLists
			.SelectMany(list => list.Attributes)
			.Select(attribute => attribute.Name switch
			{
				QualifiedNameSyntax qualified => qualified.Right.Identifier.Text,
				AliasQualifiedNameSyntax aliased => aliased.Name.Identifier.Text,
				SimpleNameSyntax simple => simple.Identifier.Text,
				_ => string.Empty,
			})
			.Any(name => name is "GeneratedCode" or "GeneratedCodeAttribute");

	/// <summary>
	/// Whether a file is one the build or a designer writes rather than a person: under <c>obj</c> or
	/// <c>bin</c>, or named the way generated C# is named.
	/// </summary>
	public static bool IsGeneratedFile(string file)
	{
		var name = Path.GetFileName(file);

		var isOutput = file.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar).Any(segment =>
			segment.Equals("obj", StringComparison.OrdinalIgnoreCase) || segment.Equals("bin", StringComparison.OrdinalIgnoreCase));

		return isOutput
			|| name.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
			|| name.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
			|| name.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase);
	}
}
