using System.Text.Json;

namespace RoseMcp.XamlStubs;

/// <summary>
/// How the generator tells its host what it did.
/// <para>
/// Roslyn constructs a generator out of an analyzer assembly by itself, so there is no callback to
/// hand it any more -- the only things a generator can emit are source and diagnostics. Source it
/// is: one extra document carrying the account as JSON on a marked comment line, which the worker
/// reads back when it enumerates generated documents anyway. A comment rather than a constant so
/// the report adds no symbol to the user's compilation, and a marker prefix so a header that grows
/// another line does not move it.
/// </para>
/// <para>
/// The shape is duplicated on the worker's side rather than shared. This crosses an analyzer
/// assembly boundary, and a shared type there means the host and the shadow copy must agree on an
/// assembly identity -- exactly the version-matching problem the generator is built to avoid. Only
/// the two constants below cross, and a const is compiled into the reader.
/// </para>
/// </summary>
public static class XamlStubReportChannel
{
	/// <summary>The document the report is written to; the worker looks it up by this name.</summary>
	public const string HintName = "__RoseMcpXamlStubReport.g.cs";

	/// <summary>The line prefix the JSON follows.</summary>
	public const string Marker = "// rosemcp-xaml-report:";

	/// <summary>
	/// Spelled out rather than taken from Environment, which a compiler extension may not touch:
	/// generated output has to be identical whatever machine produced it.
	/// </summary>
	private const string NewLine = "\r\n";

	public static string Render(XamlStubReportPayload report) =>
		"// <auto-generated/>" + NewLine
			+ "// What RoseMCP's XAML stub generation did to this project. This document exists so" + NewLine
			+ "// the worker can report it; a generator has no other way to speak to its host." + NewLine
			+ Marker + JsonSerializer.Serialize(report) + NewLine;
}

/// <summary>The account of one project's stub generation, as it crosses the boundary.</summary>
public sealed record XamlStubReportPayload
{
	public string? Dialect { get; init; }

	public string DialectReason { get; init; } = string.Empty;

	public bool DialectAmbiguous { get; init; }

	public int MarkupFileCount { get; init; }

	public int StubbedClassCount { get; init; }

	public IReadOnlyList<string> UnresolvedTypes { get; init; } = [];

	public IReadOnlyList<string> Skipped { get; init; } = [];
}
